{% set name = "cvxportfolio" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3861e7484b225141b19aba03d0bc26ffa9d058918102e0c7ef7dc4c6bc80a730

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - cvxpy
    - matplotlib-base
    - numpy
    - pandas
    - requests
    - scs

test:
  imports:
    - cvxportfolio
  commands:
    - python -m cvxportfolio.tests

about:
  home: https://cvxportfolio.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Portfolio optimization and back-testing
  dev_url: https://github.com/cvxgrp/cvxportfolio
  doc_source_url: https://github.com/cvxgrp/cvxportfolio/blob/master/README.rst

extra:
  recipe-maintainers:
    - enzbus
    - timkpaine
