{% set name = "cvxportfolio" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # no sdist provided, no tags on github
  # see https://github.com/cvxgrp/cvxportfolio/issues/67
  url: https://pypi.io/packages/py3/c/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: f506c06011f6039facffb356b89c2fb452591df7b29a196a628815ba51609532

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install {{ name }}-{{ version }}-py3-none-any.whl -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cvxpy >=1.0.6
    - matplotlib-base
    - numpy
    - pandas
    # Missing from upstream
    # see https://github.com/cvxgrp/cvxportfolio/pull/66
    - multiprocess
    - pandas-datareader

test:
  imports:
    - cvxportfolio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cvxgrp/cvxportfolio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Portfolio optimization and simulation in Python
  dev_url: https://github.com/cvxgrp/cvxportfolio

extra:
  recipe-maintainers:
    - timkpaine
