{% set name = "cvxportfolio" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4daf11b17284923cf86dd46a5d7445383769f1e2273094cfa986bf40d8fa71e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cvxpy
    - matplotlib-base
    - multiprocess
    - numpy
    - pandas
    - requests
    - scs

test:
  imports:
    - cvxportfolio
  commands:
    - python -m cvxportfolio.tests

about:
  home: https://cvxportfolio.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Portfolio optimization and back-testing
  dev_url: https://github.com/cvxgrp/cvxportfolio
  doc_source_url: https://github.com/cvxgrp/cvxportfolio/blob/master/README.rst

extra:
  recipe-maintainers:
    - enzbus
    - timkpaine
