{% set name = "cvxportfolio" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d62b3663da9634d92fdfbe78f31bbfbdd6313237d7600d6a86adf4862d1a9378

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cvxpy
    - matplotlib-base
    - numpy
    - pandas
    - requests
    - scs

test:
  requires:
    - python {{ python_min }}
  imports:
    - cvxportfolio

about:
  home: https://cvxportfolio.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Portfolio optimization and back-testing
  dev_url: https://github.com/cvxgrp/cvxportfolio
  doc_source_url: https://github.com/cvxgrp/cvxportfolio/blob/master/README.rst

extra:
  recipe-maintainers:
    - enzbus
    - timkpaine
